FROM node:20-alpine3.21 AS builder

WORKDIR /app

ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p/original
ARG VITE_CURRENCY=₹
ARG VITE_API_URL=http://localhost:5000
ARG VITE_BASE_URL=http://localhost:3000

ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_TMDB_IMAGE_BASE_URL=$VITE_TMDB_IMAGE_BASE_URL
ENV VITE_CURRENCY=$VITE_CURRENCY
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_BASE_URL=$VITE_BASE_URL

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# -----------------------------
# Production Stage
# -----------------------------
FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx","-g","daemon off;"]