# SonarCloud Configuration

sonar.organization=deepikachettiar
sonar.projectKey=Deepikachettiar_Movix
sonar.projectName=Movix

# Define path to source directories
sonar.sources=client/src,server

# Exclude dependencies and build artifacts from analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,client/src/assets/**

# Target language properties (JS/TS)
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.sourceEncoding=UTF-8
